menubar: false
height: 150
toolbar:
  - styleselect | bold italic | undo redo | image | link | table | removeformat
   
plugins:
  - image
  - link
  - table


alternate:
  selector: textarea.table-editor
  toolbar: styleselect | bold italic | undo redo | table
  plugins:
    - table

